### ISSUE TITLE
License

### ISSUE THREAD

**Issue by larshp** [se38/zJSON#21]
Hi,
Can you help adding a license to let users know how/if they can use the code?

See
https://help.github.com/articles/adding-a-license-to-a-repository/
https://choosealicense.com/

**Comment by se38** [comment]
Good idea, although there's already a license mentioned in the Readme. The license file I'll add later today.

**Comment by larshp** [comment]
Cool, I've added the license in the overview on dotabap.org, and it uses the github API, and github looks for a LICENSE file

![image](https://user-images.githubusercontent.com/5888506/34637969-2237f742-f2c2-11e7-9799-940b56d83100.png)

**Comment by se38** [comment]
Done
