### ISSUE TITLE
It takes more than 10 minutes to call method DUMPS.

### ISSUE THREAD

**Issue by comtoexe** [se38/zJSON#25]
Hi,

 I call the method DUMPS in order to format JSON data.
It takes more than 10 minutes  and happen runtimes error.

Code is as below:
  CALL METHOD LO_JSON->DUMPS
    IMPORTING
      RESULT = DATA_TAB.

**Comment by se38** [comment]
Works for me:

```
    DATA: BEGIN OF xxx,
            f1 TYPE string,
            f2 TYPE string,
          END OF xxx.

    xxx = VALUE #( f1 = 'aaa' f2 = 'bbb' ).

    DATA(json) = zcl_json_document=>create_with_data( xxx ).
    json->dumps(
      IMPORTING
        result         = DATA(dump)
    ).
```

What content do you want to "dump"?

**Comment by se38** [comment]
No answer
