### ISSUE TITLE
Performance Problem on Large Json 

### ISSUE THREAD

**Issue by mvcube** [se38/zJSON#26]
I'm encountering severe performance issues with large objects. The server returns ~50 MB of json data, a long array. The parser spends most of its time in ESCAPECHAR and GET_OFFSET_CLOSE. I've the impression that the run time increases with the square of the size of the object. 

The culprit is most probably the use of FIND ALL OCCURENCES on the complete object to search for the next un-escaped double quote or closing bracket and the following bracket pairing loop. Wouldn't it be better to implement a one time linear search over the complete document to separate it into its tokens? The result could be a table with start offset / end offset for each item. A regular expression could help to exclude escaped objects in the first place instead of the "what's the character let of me?" check.

**Comment by se38** [comment]
Hi Marcus,

yes, the performance issue is already know. But because zJSON is not meant to be used for huge JSON files (SAP has a way better kernel solution), the motivation to solve this issue isn't very high.

But feel free to develop your idea further and ask for a pull request. This is open source and lives by the contribution of the community.

Thank you,
Uwe

**Comment by mvcube** [comment]
Hallo Uwe,

danke für die Antwort. Leider bin ich GIT-Anfänger (ich verstehe es einfach
nicht, ich komme eher von SVN) und das SAP-System, auf das ich Zugriff habe,
hat keine Verbindung zu github. Um zJSON auf die Maschine zu bekommen, musste
ich daher den Umweg über einen Download gehen. Das war, auch wegen der
"Sprachbarriere" DE/EN, ein ziemlicher Akt. Ich denke noch über eine Lösung
des Performance-Problems nach, weiß aber nicht, wie ich das zurückspielen kann.

Zur Kernel-Lösung: Der Weg über die ID-Transformation erscheint mir wesentlich
umständlicher als zJSON. Erste Experimente damit hatten gezeigt, dass die
JSON-Tags dann nämlich alle GROSS geschrieben sein müssen, es sei denn, man
gibt für jedes Feld eine Umsetzung an. Das wird ziemlich grausliger Code. Eine
interne Umsetzung in XML und dann das DOM zu parsen erscheint mir reichlich
umständlich.

Ich finde zJSON richtig schick und möchte daher dabei bleiben.

Stay tuned!

-- 
Mit freundlichen Grüßen

Marcus von Cube

Am 01.05.20 um 15:20 schrieb Uwe Fetzer:

**Comment by se38** [comment]
Hallo Marcus,
wenn du keine besonderen Funktionen von zJSON benötigst, kannst du auch die Methode "simple_transformstion" verwenden. Die kann auch mit Kleinbuchstaben umgehen und verwendet die Kernel-Funktionen.
Grüße, Uwe

**Comment by se38** [comment]
Link zur [Doku](https://github.com/se38/zJSON/wiki/Usage-zJSON#simple-transformation-new-in-release-0217)

**Comment by mvcube** [comment]
Hallo Uwe,

danke für die Hinweise. Denen gehe ich gerne nach.

-- 
Mit freundlichen Grüßen

Marcus von Cube

Am Hebestumpf 6
61273 Wehrheim

Tel: 06081-5 95 27
Fax: 06081-5 63 66
Mobil: 0177-32 00 614
http://www.mvcsys.de

**Comment by se38** [comment]
Solution: simple_transformation
