### ISSUE TITLE
zabapgit error when pulling objects (see scrshot detailing error attached) 

### ISSUE THREAD

**Issue by peterli-code** [se38/zJSON#32]
Hello Uwe,

Hope you will be able to resolve as know you are a busy dev.

I attempted twice to load the objects in this github repo ZJSON today via ZABAPGIT. First system was in ABAP 1909 Dev System and second system ABAP NPL 7.52 which showed the same fault/bug?.

Please find attached scrshot when I try to pull (load) the ZJSON objects. Fails when trying to create table ZJSON_KEY_VALUE. System complain it cannot activate. When I try to create Z table manually simulating fields in src xml, I also receive activation error when using KEY (is a reserved word) as field name.

Would kindly appreciate if there is a workaround or solution to this. Thanks in advance,

Please let me know if the scrshot is/not viewable as unsure if PNG format is supported. Can resend with word format. TIA.

Kind regards

Peter Li
![Abapgit_pull_error](https://user-images.githubusercontent.com/68171678/119906925-1cb2df80-bf47-11eb-87aa-503630f7c48d.PNG)

**Comment by se38** [comment]
Hi Peter,

just imported the repository again to check your issue. No problems here (neither online nor offline/zip).
The "activation error when using KEY" is just a warning and the structure should be activated automatically. If not, try it "by hand" again and report back.

Cheers, Uwe

**Comment by peterli-code** [comment]
Hi Uwe,

Thanks for the prompt reply. The problem at my end is the zabapgit stops dead in its track and does not create the 2 objects. I checked in se11 which claims they both don't exist in system. I will see if I can get it to work with online. I will report back let you know if I can get it to upload without these errors. Strange.  
 TIA.

Regards
Peter

**Comment by peterli-code** [comment]
Hello Uwe

I was not successful in pulling all the objects (same error). Would appreciate your help in getting this table accepted. I tried to emulate  manual creation of Z table but again failed. Here are scrshots of me trying to get over the issue. I am stumped how you got it to work without encountering any issue.

![Capture1](https://user-images.githubusercontent.com/68171678/120052251-37a35380-c01c-11eb-86c3-eee608780e88.PNG)
![Capture2](https://user-images.githubusercontent.com/68171678/120052254-3a9e4400-c01c-11eb-9cf3-7e794e4c9f49.PNG)

Kind regards
Peter

**Comment by se38** [comment]
Hi Peter,
please try to create zjson_key_value as a structure, not as a transparent table.
![image](https://user-images.githubusercontent.com/5384144/120209900-7b21db80-c22f-11eb-80e9-04116a0831dd.png)

**Comment by peterli-code** [comment]
Hi Uwe
Thanks for the suggestion. I will try this out later on and let you know how I get on. Cheers.
Regards/Gruss
Peter
    On Monday, 31 May 2021, 15:45:39 BST, Uwe Fetzer ***@***.***> wrote:  
 
 


Hi Peter,
please try to create zjson_key_value as a structure, not as a transparent table.

**Comment by peterli-code** [comment]
Hello Uwe, 

After a bit of a struggle to delete the Z table, I finally succeeded to get the structure accepted and working ok, So I finally managed to get an output. Tada.   Thanks very much for sorting out the issue. 

Best regards

Peter

![Capture1](https://user-images.githubusercontent.com/68171678/120362414-f43e3300-c302-11eb-835c-81fb34e969c0.PNG)

See attached,

**Comment by se38** [comment]
Glad it worked, thanks for the feedback.
Have fun 😁
