### ISSUE TITLE
Russian char

### ISSUE THREAD

**Issue by mr-orange** [se38/zJSON#36]
Hi thanks for this nice class. I have a small question:
How to convert Json with foreign language? I can't find any char encoding in method create with data.
If I try to convert structure with russian description field text I obtain this ########### from this Инсталляция.
Please let me know.

Thanks.

**Comment by se38** [comment]
I'm currently on vacation. Will let you know when I'm back.

**Comment by mr-orange** [comment]
Hi thanks for the answer. I have resolved the problem of Russian Char. The problem was on my code during the local upload on my pc. Tomorrow I will close the issue.
Thanks for your great library and have a nice holidays.
Luca.
________________________________
Da: Uwe Fetzer ***@***.***>
Inviato: mercoledì, agosto 10, 2022 8:21 PM
A: se38/zJSON ***@***.***>
Cc: Mr_Orange ***@***.***>; Author ***@***.***>
Oggetto: Re: [se38/zJSON] Russian char (Issue #36)


I'm currently on vacation. Will let you know when I'm back.
