### ISSUE TITLE
FIND_INFINITE_LOOP + while creating the JSON

### ISSUE THREAD

**Issue by Palaniappanst** [se38/zJSON#37]
While creating a Json using zcl_json_document=>create_with_json. We face the short dump in few cases. Issue might be because statement lv_json = me->json. is not executed properly. Lv_json after this statement is }} where us me->json is having full required json. 

Request guidance to close this issue.

![image](https://user-images.githubusercontent.com/96229530/184673774-504b10c4-c8a1-4218-8dd4-540d7a6a03a4.png)
[SD.txt](https://github.com/se38/zJSON/files/9338464/SD.txt)

**Comment by se38** [comment]
Currently I'm on vacation, will look at it next week
Cheers, Uwe

**Comment by se38** [comment]
Can you paste the full JSON here? (maybe anonymize sensitive data)

**Comment by se38** [comment]
Cannot be fixed without example
